### ISSUE TITLE
Game Loop - See Also section: dead link

### ISSUE THREAD

**Issue by davidwilemski** [munificent/game-programming-patterns#295]
I doubt there's anything you can do about it besides removing the link but unfortunately the link on the game loop chapter about Unity's game loop architecture is dead: http://www.richardfine.co.uk/2012/10/unity3d-monobehaviour-lifecycle/

Fortunately, it seems that archive.org has a copy!
https://web.archive.org/web/20140808185645/http://www.richardfine.co.uk/2012/10/unity3d-monobehaviour-lifecycle/

**Comment by munificent** [comment]
Thanks for the heads up. I found a current link that I think has an even better illustration. :)
