### ISSUE TITLE
Doubly linked list remove is not constant time

### ISSUE THREAD

**Issue by richoux** [munificent/game-programming-patterns#301]
Hi Bob,

That's great we can make observations and comments on the book through github, great idea!

At the bottom of page 51 on the Observer chapter, you wrote "If we use a doubly linked list, where each observer has a pointer to both the observer after it and before it, we can remove an observer in constant time"

Well, you can't actually: you still need to go through the list to reach the observer you want to remove, and this is done in linear time at worst. Therefore, the sentence page 52 "Registering and unregistering is as fast as it was with a simple array" should also be changed. 

In addition, I found this part in contradiction with Chapter 17: linked lists prevent us from the benefit of prefetching, and moreover we have slightly heavier observers with one or two pointers.

Cheers!

**Comment by munificent** [comment]
> Well, you can't actually: you still need to go through the list to reach the observer you want to remove, and this is done in linear time at worst.

You already *have* the observer. Otherwise, how would you identify which one you wanted to remove? :)

**Comment by richoux** [comment]
Hey Bob, yes you right! I realized that a couple of days after my message but I didn't take time to modify it, my bad! So indeed, constant time to remove it, everything's good (except for the prefetcher ^^).
