### ISSUE TITLE
"Observer Pattern" Mistake

### ISSUE THREAD

**Issue by ghost** [munificent/game-programming-patterns#328]
I think I may have found a mistake in this paragraph:

"Now, when the physics engine does something noteworthy, it calls notify() like in the motivating example before. That walks the observer list and gives them all the heads up."

Shouldn't it have been "That wakes the observer list and gives them all the heads up."

Just my input :)

**Comment by JensB-tech** [comment]
No, "walks" is definitely the intended word here. He means that the notify() method will "walk" through the observer list and call onNotify() on every single observer. He means "walk" as in "iterate over".
